# Generated by Django 3.2.7 on 2021-09-30 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionaluser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='regionaluser',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='regionaluser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='regionaluser',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='regionaluser',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sending.profile', verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='regionaluser',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sending.region', verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='regionaluser',
            name='username',
            field=models.CharField(max_length=60, verbose_name='Nombre de Usuario'),
        ),
    ]
